# site properties and page defaults
title: Pheelab
subtitle: 
description: Prof. Louis Phee’s Lab
header: images/endomaster.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: msjphee@ntu.edu.sg
  orcid: 0000-0002-9709-5848
  google-scholar: zmILNKkAAAAJ&hl
  github: pheelab
#  twitter: pheelab
#  youtube: pheelab

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
